### ISSUE TITLE
Double arguments in training script

### ISSUE THREAD

**Issue by DominikFle** [KIT-MRT/masked-fusion-360#1]
In the `train_masked_fusion` [script](https://github.com/KIT-MRT/masked-fusion-360/blob/main/src/masked_fusion_360/train_masked_fusion.py) there are doubled arguments in the creation of the fusion encoder:
The vit_dim is doubled
```
        fusion_encoder = FusionEncoder(
        vit_dim=args.lidar_encoder_dim,
        patch_size=args.lidar_encoder_patch_size,
        vit_dim=args.lidar_encoder_dim,
        vit_mlp_dim=args.lidar_encoder_mlp_dim,
    )
```

**Comment by roydenwa** [comment]
Thanks for reporting. Will be removed by this [PR](https://github.com/KIT-MRT/masked-fusion-360/pull/2).
